list_of_prefix = ['Policy Number[\s]*[:]*', 'Policy[\s]?[#]?[:]?', 'Policy (ID)?', 'Plan ID number[:]*', 'Endorsement',
                  'Certificate Number[:]*']
# 'Computer Glasses Benefit ID number[:]*'

#Rules

list_data = {'Policy Number': ['[0-9]{9}\s', '[0-9]{10}\s', '[0-9]{4}[-][0-9]{2}[-][0-9]{2}[-][0-9]{2}\s',
                                       '[A-Z]{1}[0-9]{2} [0-9]{4}[-][A-Z]{1}[0-9]{2}[-][0-9]{2}\s',
                                       '[0-9]{3} [0-9]{3} [0-9]{3}\s', '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{6}\s',
                                       '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{11}\s',
                                       '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{14}\s',
                                       '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{13}\s',
                                       '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{8}\s', '[0-9]{2}-[0-9]{6}\s',
                                       '[A-Z]{2}[0-9]{7}\s', '[A-Z]{3}[0-9]{7}-[0-9]{2}\s',
                                       '[0-9]{2} [0-9]{3} [0-9]{3}\s', '[0-9]{7}\s', '[0-9]{5}\s',
                                       '[a-zA-Z0-9]{3}-[0-9]{3}-[0-9]{6}-[0-9]{2} [a-zA-Z0-9]{1} [a-zA-Z0-9]{1}\s',
                                       '[\w]{3} [0-9]{1}-[0-9]{2}-[0-9]{2}-[0-9]{2}\s',
                                        '[\w]{3}[\s]*[0-9]{7}\s', '[0-9]{8}\s',
                                       '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{10}\s',
                                       '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{6}\s',
                                       '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{8}\s',
                                       '[a-zA-Z0-9]{2}-[a-zA-Z0-9]{2}-[a-zA-Z0-9]{4}[-]*[—]*[0-9]{1}\s',
                                       '[a-zA-Z][3] [0-9]{7} [0-9]{2}\s',
                                       '[a-zA-Z0-9][3] [0-9]{4}-[a-zA-Z0-9][3]-[0-9]{2}','[0-9]{5}\s']}
list_data_copy = {'Policy Number': ['[0-9]{8}\s', '[0-9]{4}[-][0-9]{2}[-][0-9]{2}[-][0-9]{2}\s',
                               '[A-Z]{1}[0-9]{2} [0-9]{4}[-][A-Z]{1}[0-9]{2}[-][0-9]{2}\s',
                               '[0-9]{3} [0-9]{3} [0-9]{3}\s',
                               '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{11}\s',
                               '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{14}\s',
                               '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{8}\s', '[0-9]{2}-[0-9]{6}\s',
                               '[A-Z]{2}[0-9]{7}\s', '[A-Z]{3}[0-9]{7}-[0-9]{2}\s',
                               '[0-9]{2} [0-9]{3} [0-9]{3}\s',
                               '[a-zA-Z0-9]{3}-[0-9]{3}-[0-9]{6}-[0-9]{2} [a-zA-Z0-9]{1} [a-zA-Z0-9]{1}\s',
                               '[\w]{3} [0-9]{1}-[0-9]{2}-[0-9]{2}-[0-9]{2}\s',
                               '[\w]{3}[\s]*[0-9]{7}\s',
                               '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{10}\s',
                               '(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{8}\s',
                               '[a-zA-Z0-9]{2}-[a-zA-Z0-9]{2}-[a-zA-Z0-9]{4}[-]*[—]*[0-9]{1}\s',
                               '[a-zA-Z][3] [0-9]{7} [0-9]{2}\s',
                               '[a-zA-Z0-9][3] [0-9]{4}-[a-zA-Z0-9][3]-[0-9]{2}']}

list_data2 = {'VIN': ['(?=[^\W\d_]*\d)(?=\d*[^\W\d_])[^\W_]{17}']}

date_list = {'Date': ['[0-9]{2}-[0-9]{2}-[0-9]{4}', '[0-9]{2}-[0-9]{2}-[0-9]{2}', '[A-Za-z]{3} [0-9]{1}, [0-9]{4}',
             '[A-Za-z]{3} [0-9]{1},[0-9]{4}', '[0-9]{2}/[0-9]{2}/[0-9]{4}',
             '((?:January|February|March|April|May|June|July|August|September|October|November|Dececmber)[\s]?[\d]{1,2},[\s]?[\d]{4})',
             '((?:Jan|Feb|Mar|Apr|May|June|July|Aug|Sept|Oct|Nov|Dec)[\s]?[\d]{1,2},[\s]?[\d]{4})',
             '[0-9]{1}/[0-9]{2}/[0-9]{4}']}

product_type = {'Auto Insurance': ['auto insurance', 'automobile insurance', 'vehicle identification number', 'vehicle year'],
                'Umbrella insurance': ['umbrella insurance', 'umbrella declarations'],
                'Life Insurance': ['DEATH BENEFIT', 'VIN', 'term life',
                                   'life insurance benifit'],
                'Renters insurance': ['renter', 'renters policy', 'renters insurance policy',
                                      'renters binding agreement'], 'Jewelry insurance': 'jewel',
                'Dental insurance': '[\s]Dental', 'Homeowners insurance': 'Homeowner',
                'Vision insurance': ' Vision Care',
                'Condo insurance': 'Combination Dwelling', 'Flood insurance': ['Flood Insurance', 'Homeowner'],
                'Medical insurance': 'Medical Plan', 'Store insurance': 'self-storage tenant',
                'Visitor insurance': 'Declaration of Medical', 'Travel insurance': 'Declaration of Coverage',
                }

product_type_1 = {'Auto Insurance': ['auto insurance', 'automobile insurance', 'vehicle identification number',
                                     'vehicle year', 'VIN', 'auto policy'],
                'Umbrella insurance': ['umbrella insurance', 'umbrella declarations', 'umbrella'],
                'Life Insurance': ['DEATH BENEFIT', 'term life',
                                   'life insurance benifit'],
                'Renters insurance': ['renter', 'renters policy', 'renters insurance policy',
                                      'renters binding agreement'], 'Jewelry insurance': ['jewel'],
                'Dental insurance': ['[\s]Dental'], 'Homeowners insurance': ['Homeowner'],
                'Vision insurance': [' Vision Care'],
                'Condo insurance': ['Combination Dwelling'], 'Flood insurance': ['Flood Insurance'],
                'Medical insurance': ['Medical Plan'], 'Store insurance': ['self-storage tenant'],
                'Visitor insurance': ['Declaration of Medical'], 'Travel insurance': ['Declaration of Coverage'],
                }

Insurer_dict = {'AIC': ['Assurant Insurance Center'],
                 'AIG': ['American General Life Insurance Company'],
                 'ASI': ['American Strategic Insurance Corp', 'ASI LLOYDS'],
                 'Allianz': ['Allianz global assistance'],
                 'Allstate': ['ALLSTATE NEW JERSEY PROPERTY AND CASUALTY INSURANCE COMPANY'],
                 'Covenant': ['Covenant Insurance Company'],
                 'Drive New Jersey Insurance Company': ['Drive New Jersey Insurance Company'],
                 'Eyemed Vision Care': ['eyemedvisioncare.com'],
                 'Franklin Mutual Insurance': ['FMI Insurance Company'],
                 'Geico': ['GOVERNMENT EMPLOYEES INSURANCE COMPANY',
                              'geico.com',
                              'GEICO CASUALTY COMPANY',
                              'GEICO SECURE INSURANCE COMPANY',
                              'GEICO Insurance Agency, LLC',
                              'GEICO Property Insurance Program'],
                 'Great American Insurance': ['Great American Assurance Company'],
                 'IMG': ['Sirius International Insurance Corporation (publ)'],
                 'Jewelers Mutual': ['JM Insurance Group'],
                 'Lemonade': ['LEMONADE INSURANCE COMPANY'],
                 'Liberty Mutual': ['Liberty Mutual'],
                 'MetLife': ['MetLife'],
                 'NAC': ['North American Company'],
                 'NFP': ['NFP Property & Casualty Services'],
                 'New York Life': ['New York Life Insurance Company'],
                 'Propgressive': ['Progressive Advanced Insurance Co',
                                  'Progressive Garden State Ins Co',
                                  'Progressive Casualty Ins. Co.',
                                  'Progressive Corporation'],
                 'Root': ['Root Insurance Company'],
                 'State Farm': ['State Farm Fire and Casualty Company',
                                  'State Farm Insurance Companies'],
                 'Stillwater': ['STILLWATER INSURANCE GROUP',
                                  'STILLWATER PROPERTY AND CASUALTY INSURANCE COMPANY'],
                "Lloyd's of London":["Lloyd's of London"],
                'Allianz Global Assistance':['Allianz Global Assistance']}
